name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: corepack enable
    - run: pnpm install
    - run: pnpm run build --if-present
    - run: pnpm run test:coverage

    - name: Codecov
      uses: codecov/codecov-action@v3
